### ISSUE TITLE
[feature request] expose systems to checks

### ISSUE THREAD

**Issue by JeremiahSecrist** [snowfallorg/lib#108]
I recently started using the project as it solves my organizational issues. That being said, I wanted a way to check on NixOS configurations using the `runNixOSTest` feature. I envisioned that the systems would already have exposed recipes that can be utilized. 
To note it requires that they be non-evaluated by `lib.nixosSystem`. 
Something like this:

``` 
{ lib, pkgs, systems }:
pkgs.testers.runNixOSTest {
  name = "test-name";
  nodes = {
    laptop = systems.x86_64-linux.laptop;
    testScript = { nodes, ... }: ''
      # ...
    '';
  }
```

This would need to exist in the checks directory. Let me know if this makes sense or if more explanation is needed.

links:
https://nix.dev/tutorials/nixos/integration-testing-using-virtual-machines.html

**Comment by jakehamilton** [comment]
You should be able to access flake outputs like your system configurations via `inputs.self` 👍

**Comment by JeremiahSecrist** [comment]
> You should be able to access flake outputs like your system configurations via `inputs.self` 👍

I feel silly for not thinking of that. That solves getting to the atter sets. I probably also just make each system a module to be enabled and grab that inside testing.
