### ISSUE TITLE
How do I access a NixOS configuration from inside a home-manager module?

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/lib#110]
I am working on a module for Plasma 6 and making launchers. For the most part this is going well, but for Steam I can't just reference the Steam package directly as that causes a new instance of Steam without the configuration I want to be installed. What I'm trying to do is reference the actual package that the NixOS module I have for Steam installed. 

I figured referencing config.programs.steam.package would work, but alas not. 

I know there's a way to get to home-manager configs from within a NixOS module, how do I do it the other way around so I can get the right path to the correct package?

**Comment by jakehamilton** [comment]
You want to use the osConfig arg that home-manager provides. You can find a mention of it in the home-manager docs.

https://nix-community.github.io/home-manager/index.xhtml#sec-usage-configuration
