### ISSUE TITLE
Use deploy-rs checks with snowfall

### ISSUE THREAD

**Issue by fiinnnn** [snowfallorg/lib#112]
Hey, I set up [deploy-rs](https://github.com/serokell/deploy-rs) a while ago and only recently noticed the checks aren't included in the flake output.

I added the checks like in the deploy-rs readme:
```nix
# ./flake.nix outputs
lib.mkFlake {
  # cut

  checks = builtins.mapAttrs (system: deploy-lib: deploy-lib.deployChecks inputs.self.deploy) inputs.deploy-rs.lib;
};
```

But when running `nix eval .#checks` I get the following result:
```
{ aarch64-darwin = { }; aarch64-linux = { }; x86_64-darwin = { }; x86_64-linux = { }; }
```

I'm guessing this is because snowfall also manages checks because when I add a check with snowfall it does work, for example:
```nix
# ./checks/pre-commit/default.nix
{
  inputs,
  system,
  ...
}:
inputs.pre-commit-hooks.lib.${system}.run {
  src = ../..;
  hooks = {
          alejandra.enable = true; # bad formatting to check if it works
  };
}
```

```
$ nix flake check
error: builder for '/nix/store/...-pre-commit-run.drv' failed with exit code 1;
       last 10 log lines:
       > --- a/checks/pre-commit/default.nix
       > +++ b/checks/pre-commit/default.nix
       > @@ -6,6 +6,6 @@
       >  inputs.pre-commit-hooks.lib.${system}.run {
       >    src = ../..;
       >    hooks = {
       > -          alejandra.enable = true;
       > +    alejandra.enable = true;
       >    };
       >  }
```

Is there a way to add the deploy-rs checks in the same way or have snowfall not overwrite the checks attribute?

**Comment by fd** [comment]
I'm running into the same issue.

**Comment by jakehamilton** [comment]
Hey! This definitely should be surfaced in the docs, my bad!

Can you try putting your checks in outputs-builder instead of the call to mkFlake? The implementation in Snowfall Lib works the same as with packages so overrides should be able to be specified in there 👍

**Comment by fiinnnn** [comment]
Ah got it, yes putting it in `outputs-builder` works:
```nix
# ./flake.nix
lib.mkFlake {
  outputs-builder = channel: {
    checks = inputs.deploy-rs.lib.${channel.nixpkgs.system}.deployChecks inputs.self.deploy;
  };
};
```

That resolves the issue so I'll go ahead and close this, thanks for the help everyone!
