### ISSUE TITLE
Set a package/module as default package/module

### ISSUE THREAD

**Issue by Svenum** [snowfallorg/lib#117]
I try to port the official Solaar-Flake (https://github.com/Svenum/Solaar-Flake) to Snowfall, but I dont find a way to make the solaar package/module the default als well. I would like to keep them named solaar but I want also be backward compatible with:
`solaar.nixosModules.default` and `solaar.packages.default`. Is there a way?

Current workaround:
Naming the folder `modules/nixos/default` and `modules/packages/default` but I want to name it `modules/nixos/solaar` / `packages/solaar` and make an alias on it so I can call the `default` module/package.

I hope you understand? :sweat_smile:

**Comment by pinkcreeper100** [comment]
https://snowfall.org/guides/lib/alias/

**Comment by Svenum** [comment]
Thanks man. I did not saw it. :+1:
