### ISSUE TITLE
How to create recursive outputs?

### ISSUE THREAD

**Issue by yajo** [snowfallorg/lib#118]
For example, let's say I want to add one check for each home, nixos module and package. Do I have to create one folder for each? Can't I use one function and recurse in those outputs, and generate tests based on them?

It'd be OK to have folders like `checks/{homes,nixos-modules,packages}/default.nix`, though.

**Comment by jakehamilton** [comment]
You can use `outputs-builder` instead for cases like this where you want to construct checks programmatically.

**Comment by yajo** [comment]
Ah it's documented, I missed it. Thank you! 
https://snowfall.org/guides/lib/generic/#outputs-builder
