### ISSUE TITLE
Nested module not exported correctly.

### ISSUE THREAD

**Issue by vic** [snowfallorg/lib#12]
Creating a nested `foo/bar` module does not export at expected attribute path.

Expected `.#nixosModules."foo/bar"` as documented on README (and also as used in jakehamilton/config) but instead it was exported as `.#nixosModules.bar` 

The following shell session reproduces this bug.
```
% nix flake init -t github:snowfallorg/templates#module
wrote: /hk/bla/flake.nix
wrote: /hk/bla/modules/snowfall/default.nix
wrote: /hk/bla/modules/snowfall
wrote: /hk/bla/modules

% mkdir modules/foo && mv modules/snowfall modules/foo/bar

% nix flake show
warning: creating lock file '/hk/bla/flake.lock'
path:/hk/bla?lastModified=1686187812&narHash=sha256-qN6inpCUvCbgaMH4pJILAKMvQJ67Wvm7+cMYRO+lRvY=
├───lib: unknown
├───nixosModules
│   └───bar: NixOS module
```

**Comment by vic** [comment]
Works when using `dev` branch, as `jakehamilton/config` does.

```
    snowfall-lib.url = "github:snowfallorg/lib/dev";
```

**Comment by jakehamilton** [comment]
Hey! Yes, there are some changes on the dev branch that include some breaking ones. Right now you can stick with the current release on `main` to be safe, but if you need any of the features/fixes that are on dev then you'll have to pull Snowfall Lib in from there until v2 is released :)

**Comment by jakehamilton** [comment]
Hi @vic, please give the latest version of Snowfall Lib a try! Modules are now exported in a way that will not conflict when the parent directory is the same.
