### ISSUE TITLE
Channels not available in modules

### ISSUE THREAD

**Issue by yajo** [snowfallorg/lib#120]
It would be a very useful feature.

This way, for example, one could define stable modules while still getting some packages from the unstable channel:

```nix
{channels, pkgs, ...}: {
  environment.systemPackages = [pkgs.git channels.nixpkgs-unstable.git-aggregator];
}
```

**Comment by jakehamilton** [comment]
I don't have any plans to add this feature right now. You can use overlays instead if you want access to unstable packages in addition to a stable package set.
