### ISSUE TITLE
snowfallorg.users.<user>.home does nothing on darwin

### ISSUE THREAD

**Issue by pupbrained** [snowfallorg/lib#123]
Hi, I've been using snowfall-lib to manage NixOS for a while and I wanted to try getting my flake for it working with macOS too. I've moved everything over but now, whenever I try to rebuild my configuration, home-manager things are not run at all and I don't get anything defined in snowfallorg.users.<user>.home.config.

I have the configuration up here: https://git.pupbrained.xyz/pupbrained/nix-config/src/commit/5b0a9850bc663aab9a442652eaa58ce4bbef0f19/systems/aarch64-darwin/canis/default.nix#L112

I assume I'm most likely just missing an option but I've looked over everything 3+ times now and I still haven't figured anything out. Any help would be appreciated.

**Comment by jakehamilton** [comment]
It seems like the commit that wasn't working in your configuration did not include a `homes/aarch64-darwin/` home configuration. For compatibility, automatic Home-Manager and user management is only enabled when a home is present.
