### ISSUE TITLE
Overlay arguments

### ISSUE THREAD

**Issue by SandWoodJones** [snowfallorg/lib#129]
I've written this overlay for `pkgs.stremio`:
```nix
{ useBlackIcon ? false, ... }: final: prev: {
  stremio = prev.stremio.overrideAttrs (oldAttrs: {
    patches = (oldAttrs.patches or []) ++ prev.lib.optional useBlackIcon ./black-tray-icon.patch;
  
    postInstall = ''
      ${oldAttrs.postInstall}
      mv $out/share/applications/smartcode-stremio.desktop $out/share/applications/com.stremio.stremio.desktop
    '';
  });
}
```
I can't figure out how I'm supposed to pass the `useBlackIcon` parameter. I install stremio through my home configuration:
```nix
{ lib, config, inputs, pkgs, ... }: {
  [...]
  home.packages = with pkgs; [
    stremio
    # I've tried (stremio.override { useBlackIcon = true; }) but it didn't work
  ];
  [...]
}
```

**Comment by jakehamilton** [comment]
I don't think this is quite the best way to handle this kind of customization. Nixpkgs makes modifications like these difficult to do regardless. One solution would be to create a different package attribute for this altered version, such as `stremio-with-black-icon`.
