### ISSUE TITLE
Support for 32-bit architectures like i686-linux

### ISSUE THREAD

**Issue by kb01guy** [snowfallorg/lib#146]
Hi, 
in the Winter Times, I decided to do some Retro-Computing and Nix-Up my old Lenovo S10 (Intel Atom N270, 2GB Ram and 32bit Architecture).
I am aware that this Platform isn't even officially Supported by NixOS anymore and am ready to contribute if I am able to Fix Things.

I get the `error: attribute 'i686-linux' missing at /nix/store/84m9nfg7kamv5va1fkk2iszbn5q2mavh-source/lib/mkFlake.nix:83:25:`
```
getChannels = system: self.pkgs.${system};
                      ^
getNixpkgs = host: (getChannels host.system).${host.channelName};
```

While digging, I found this in [snowfall-lib/system/default.nix Line 230](https://github.com/snowfallorg/lib/blob/cfeacd055545ab5de0ecfd41e09324dcd8fb2bbb/snowfall-lib/system/default.nix#L230C1-L231C31):
```
    create-system = {
      target ? "x86_64-linux",
```
This looks like only x86_64-linux is supported. 
Is it possible to directly specify a system in the flake.nix as a Workaround? And how complicated would it be to mimic the x68_64-linux behavior for i686-linux to add support for it?

Thanks a Lot for any Help or Input, Snowfall-Lib is amazing :)

Update 1: My Flake is at https://git.kb-one.de/kb01/aux-config/src/branch/host-Rubtrm Commit [d2d1dfa995](https://git.kb-one.de/kb01/aux-config/src/commit/d2d1dfa9952eb3cdec20490fd15cef7c4d4ff170) and the Host is Rubtrm

**Comment by jameslounds** [comment]
I think you just need to add 
```nix
supportedSystems = inputs.snowfall-lib.inputs.flake-utils-plus.lib.defaultSystems ++ ["i686-linux"];
```

To your `mkFlake` call in `flake.nix`.

By default, `flake-utils-plus` (where your error message is from) only makes `pkgs` for `supportedSystems`, which defaults to `defaultSystems`. However, if you pass this arg into `snowfall`'s `mkFlake`, it will make its way down to `flake-utils-plus`' `mkFlake` args. I don't have an `i686-linux` system I can test with, but the error was present before in the `nix repl` with `:lf .` and `nixosConfigurations`, and isn't after this line has been added.

Afaik there is no documentation for this, so all of this is from me reading source code and my nix knowledge isn't fantastic, so take what I say with a grain of salt.

**Comment by jameslounds** [comment]
@kb01guy can you confirm if this worked? I see [f9003d](https://git.kb-one.de/kb01/aux-config/src/commit/f9003db1670631cb32abdf7d7e17a7f553973f34) which adds the `supportedSystems` line was merged into your `main` branch.

**Comment by kb01guy** [comment]
Yes, it worked. I am so sorry, for the Delay.
