### ISSUE TITLE
Multiple home-manager activations darwin

### ISSUE THREAD

**Issue by khaneliman** [snowfallorg/lib#17]
I haven't seen this behavior on NixOS, but see it whenever I switch on darwin. Not sure if it's something weird in my [config](https://github.com/khaneliman/khanelinix), or in lib. 
<img width="689" alt="Screenshot 2023-08-30 at 4 17 25 PM" src="https://github.com/snowfallorg/lib/assets/1778670/cac4a42d-5beb-45a1-aa95-c9c7ce68b6bc">

**Comment by jakehamilton** [comment]
Interesting. I'm not really sure why that may be the case. I think the best course of action for trying to debug it is to build the system and look at the activation script used. I'm not sure why it would be calling home-manager multiple times...

**Comment by khaneliman** [comment]
![image](https://github.com/snowfallorg/lib/assets/1778670/ae7a34fa-83fc-4e0e-819f-46c7fa79d546)

**Comment by khaneliman** [comment]
Looks like it was doing it for each time I import the home-manager module. When I remove the duplicate import within the system.modules.darwin, it only calls it twice (once for home and once for darwin/home/default.nix). If I remove the darwin import it calls it once. 

<img width="549" alt="image" src="https://github.com/snowfallorg/lib/assets/1778670/63c60075-3c85-468b-8cb4-79611c9e494e">
<img width="694" alt="image" src="https://github.com/snowfallorg/lib/assets/1778670/13bbf142-45f4-4fbe-8579-012f7d5dd111">

**Comment by jakehamilton** [comment]
> Looks like it was doing it for each time I import the home-manager module. When I remove the duplicate import within the system.modules.darwin, it only calls it twice (once for home and once for darwin/home/default.nix). If I remove the darwin import it calls it once.
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/1778670/264814960-63c60075-3c85-468b-8cb4-79611c9e494e.png"> <img alt="image" width="694" src="https://user-images.githubusercontent.com/1778670/264815111-13bbf142-45f4-4fbe-8579-012f7d5dd111.png">

Ah yeah that makes sense. The latest version of Snowfall Lib automatically imports home-manager if you have it in your inputs. Additional imports may cause some issues. Should be fine to keep it removed from your system modules and let Snowfall Lib take care of it :+1:

**Comment by khaneliman** [comment]
Thanks, I never submitted my follow up asking about that. I noticed home-manager functioned when I removed all imports lol. Does it do that for all inputs because I also saw interesting behavior when trying to add agenix as an input.

**Comment by jakehamilton** [comment]
There is a special case for home-manager and nix-darwin, but that is it. The issue you saw with agenix is (unfortunately) due to a problem with flake-utils-plus and how it checks for Nix channels. I haven't gotten around to submitting a fix 😅
