### ISSUE TITLE
`agenix` input causes `devShell` breakage

### ISSUE THREAD

**Issue by arichtman** [snowfallorg/lib#18]
Hi Jake, I'm enjoying SnowFall Lib as usual so thanks!

However when I try to add Agenix as a flake input it breaks - something about the devShell doesn't like it :(

I've created a minimal reproduction here

https://github.com/arichtman/nix/tree/broken-shell

![image](https://github.com/snowfallorg/lib/assets/10679234/cd561a7b-f85f-4567-bf6a-85f6e1b44a2e)

**Comment by jakehamilton** [comment]
Heya, unfortunately this is an issue with flake-utils-plus in how it checks for nixpkgs channels. Agenix exports a legacy packages output, but Agenix doesn't check to make sure it provides the specific system it's looking for.

**Comment by arichtman** [comment]
Ok, thanks for your time!

**Comment by jakehamilton** [comment]
This will be fixed by https://github.com/gytis-ivaskevicius/flake-utils-plus/pull/135
