### ISSUE TITLE
Docker system being recognized as Digital Ocean 

### ISSUE THREAD

**Issue by usmcamp0811** [snowfallorg/lib#19]
I could just be doing dumb things but I think something is thinking that my `docker` system should be a digital ocean system. This is my systems folder:

```sh
├── systems
│   ├── x86_64-amazon
│   │   └── base
│   │       └── default.nix
│   ├── x86_64-docker
│   │   └── container
│   │       └── default.nix
```

when I hop into the `nix repl` I only see `doConfigurations` 

```
outputs._snowfall             outputs.devShells             outputs.lib                   outputs.pkgs
outputs.amazonConfigurations  outputs.doConfigurations      outputs.nixosConfigurations   outputs.templates
outputs.checks                outputs.homeConfigurations    outputs.nixosModules
outputs.darwinModules         outputs.homeModules           outputs.overlays
outputs.deploy                outputs.isoConfigurations     outputs.packages
nix-repl> outputs.
```

is there something in Snowfall Lib that might be causing this? Or would this be upstream with `nixos-generators` ya think? 

Or is it the more likely case that I am an idiot and did something dumb?

**Comment by usmcamp0811** [comment]
Did some playing around with `./snowfall-lib/system/virtual-systems.nix` I was able to build a Docker image by replacing `do` with `docker`. If I have both `do` and `docker` in that file it seems to default to `do` .

**Comment by jakehamilton** [comment]
Thanks for reporting this! Docker isn't currently in the supported virtual systems list, but we can add it. Due to how the code checks for which system is used, the order of that list is important. If we add "docker" before "do" then it should work just fine 👍
