### ISSUE TITLE
error: module must be a function or an attribute set

### ISSUE THREAD

**Issue by gaelreyrol** [snowfallorg/lib#2]
Hi!

First I'd like to thanks you for your work, I have been thinking for a long time of what would be the structure for my NixOS configuration and what you are providing with this package seems to be the best option.

Here is my configuration with swowflake lib in a branch: https://github.com/gaelreyrol/nixos-config/tree/feat/modules

The problem I encounter is a cryptic error while running a simple `nix flake check`. With the option `--show-trace` here is the output:
```
warning: unknown flake output 'lib'
error: module must be a function or an attribute set

       … while checking the NixOS module 'nixosModules.nix'

       at /nix/store/x8rpd5nhip722lxdxvxp90ax6p329v9c-5bvwy7jpbaw9jrdgbc6b5v9m739jg9zf-source/lib/module/default.nix:31:13:

           30|           modules // {
           31|             ${metadata.name} = metadata.path;
             |             ^
           32|           };

       … while checking flake output 'nixosModules'

       at /nix/store/x8rpd5nhip722lxdxvxp90ax6p329v9c-5bvwy7jpbaw9jrdgbc6b5v9m739jg9zf-source/lib/flake/default.nix:117:9:

          116|
          117|         nixosModules = modules;
             |         ^
          118|
```

I assume it as something to do with my own `nix` module which is inspired from @jakehamilton 's one [here](https://github.com/jakehamilton/config/blob/main/modules/nix/default.nix).

But my little experience does not allow me to interpret as I would like this error.

Maybe it is not the right place to report this or ask for help, please tell me if it not.

Many thanks in advance for your answer!

Regards

**Comment by jakehamilton** [comment]
Hey @gaelreyrol 👋 

This was a bug in Nix that was fixed last month. Make sure you're using the latest version of Nix (currently 2.13) if you're going to be running that check.

https://github.com/NixOS/nix/issues/6866

**Comment by gaelreyrol** [comment]
Thanks! It solved my error but I have others :grimacing:. I hope I will manage to solve them!

Do you plan to open a Matrix room to allow folks that what to use your lib to discuss without creating issues ?

**Comment by jakehamilton** [comment]
@gaelreyrol that's a good suggestion, I'll definitely consider it :)
