### ISSUE TITLE
clarity on v2 snowfall and migration

### ISSUE THREAD

**Issue by biggiesmallsAG** [snowfallorg/lib#21]
Hi Jake,

Since moving to v2 ive been having difficulties getting my existing neovim package working. Previously i had my customized version of neovim calling packages under my namespace as inputs to the override.

Output of nix flake show since v2 update
![image](https://github.com/snowfallorg/lib/assets/17421028/94c1ef2f-01e0-447f-8eaf-3408e0ce17d8)

Im missing the package "neovim-vimplug" as defined in my packages:

![image](https://github.com/snowfallorg/lib/assets/17421028/28ed3ae8-8fd0-481f-8975-cc7b523e0e72)

Here is how my flake.nix is setup:

![image](https://github.com/snowfallorg/lib/assets/17421028/19604cdf-1218-4cc6-b6ad-67b0e9599794)

Im probably doing something dumb, ive been through your v2 doco but im still not getting this customized package to show up and be useable. Any help would be appreciated.

**Comment by jakehamilton** [comment]
Hmm, it doesn't seem right that the package is the showing up. Can you share your full configuration in a GitHub repo? I don't think I see anything obviously wrong from the screenshots you shared.

**Comment by jakehamilton** [comment]
Hey @biggiesmallsAG, if you're able to share your full flake in a GitHub repository I can try to take a look. Otherwise I'm going to close this issue for now. If you are still having trouble and end up putting your configuration up on GitHub, please feel free to mention it here and reopen the issue.
