### ISSUE TITLE
Nixpkgs.config failed assertion 

### ISSUE THREAD

**Issue by khaneliman** [snowfallorg/lib#24]
Hey, just wondering how to resolve this issue now with latest in unstable introduced from https://github.com/NixOS/nixpkgs/commit/eb8ce7930d14dafcc7eff56c2f9efca6a3b2f622. 

```
Failed assertions:
       - Your system configures nixpkgs with an externally created instance.
       `nixpkgs.config` options should be passed when creating the instance instead.
```

**Comment by jakehamilton** [comment]
I've just updated the flake-utils-plus input which should have a fix for it. Can you try updating your `snowfall-lib` input to at least `v2.1.1` (current latest)?

**Comment by khaneliman** [comment]
resolved with https://github.com/snowfallorg/lib/commit/92803a029b5314d4436a8d9311d8707b71d9f0b6

**Comment by jakehamilton** [comment]
Glad to hear it!
