### ISSUE TITLE
Disko Support

### ISSUE THREAD

**Issue by jacobranson** [snowfallorg/lib#25]
How can disko be used in conjunction with Snowfall Lib? I get the following:

```
error: flake 'git+file:///var/home/jacob/Projects/alaska' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."anchorage".config.system.build.diskoScript', 'legacyPackages.x86_64-linux.nixosConfigurations."anchorage".config.system.build.diskoScript' or 'nixosConfigurations."anchorage".config.system.build.diskoScript'
``` 

I added the disko input to the flake, then added

```
system.modules = [
  inputs.disko.nixosModules.disko
];
```

inside the `inputs.snowfall-lib.mkFlake` block.

Inside my `systems/x86_64-linux/anchorage/default.nix`, I added

```
  imports =[
    ./hardware-configuration.nix
    ./disk-configuration.nix
  ];
```

And inside disk-configuration.nix I have it looking like this:

```
{ lib, ... }:
{
  lib.disko.devices = {
  # stuff
  };
}
```

I am brand new to this so apologies if I am missing something obvious. I am unsure if this is a mistake in my configuration or something Snowfall Lib doesn't support.

**Comment by jacobranson** [comment]
Ignore me, I figured out a lot since posting this.

**Comment by JeanMertz** [comment]
It's always annoying to run into the same issue, only to have an "I solved it" comment, without actually explaining what the solution was.

If/when I find out what caused it for me, I'll report back here.

**Comment by jakehamilton** [comment]
@JeanMertz make sure you are specifying the right name for configuration. If you are adding the module to every system, you should be using `systems.modules`. For a single host it should be `systems.hosts.my-host.modules`.

https://snowfall.org/guides/lib/systems/

**Comment by JeanMertz** [comment]
@jakehamilton no matter where I put it, I keep getting this error:

> error: flake 'path:.' does not provide attribute 'packages.aarch64-darwin.nixosConfigurations."Takodana".config.system.build.diskoScript', 'legacyPackages.aarch64-darwin.nixosConfigurations."Takodana".config.system.build.diskoScript' or 'nixosConfigurations."Takodana".config.system.build.diskoScript'

This is how I'm trying to run it:

```shell
nix run github:nix-community/nixos-anywhere -- \
                                      --flake path:.#$MACHINE \
                                      --build-on-remote \
                                      --no-reboot \
                                      --stop-after-disko \
                                      root@$MACHINE
```

I tried the following:

```nix
      systems.hosts.Takodana.modules = with inputs;
        [
          disko.nixosModules.disko
        ];
```

```nix
      systems.modules.nixos = with inputs; [
        disko.nixosModules.disko
      ];
```

Also, in `Takodana/default.nix` I tried:

```nix
  imports = [
    inputs.disko.nixosModules.disko
  ];
```

I wonder if I should be setting `outputs-builder` so that it can actually find `diskoScript`, but I don't know how to configure it, if that's the case.

**Comment by jakehamilton** [comment]
@JeanMertz can you share a git repo with your flake?

**Comment by JeanMertz** [comment]
@jakehamilton sorry, no repo available yet. I still have a bunch of secrets I need to remove/encrypt before I can push up the code.

**Comment by JeanMertz** [comment]
I think this might have been an entirely _me_ thing (combined with the always challenging to parse (or just downright impossible to bisect) Nix errors):

While I was in the process of setting up things, I had `disko.devices = {}` configured. This, it turns out, results in the error

```
error: flake 'path:.' does not provide attribute 'packages.aarch64-darwin.nixosConfigurations."Takodana".config.system.build.diskoScript', 'legacyPackages.aarch64-darwin.nixosConfigurations."Takodana".config.system.build.diskoScript' or 'nixosConfigurations."Takodana".config.system.build.diskoScript'
```

Only after I actually populated the empty set with disk details, did the error go away.
