### ISSUE TITLE
Wrong documentation for `system.modules`

### ISSUE THREAD

**Issue by RuRo** [snowfallorg/lib#26]
Commit 17ef1c563d6dfd2e55dfbd1fbbfe46abc088ef0a refactored the `systems.modules` API. After that commit you need to pass global modules like this
```nix
inputs.snowfall-lib.mkFlake {
  ...
  systems.modules.nixos = [ ... ];
  systems.modules.darwin = [ ... ];
};
```
instead of
```nix
inputs.snowfall-lib.mkFlake {
  ...
  systems.modules = [ ... ];
};
```
but the [documentation still advertises the old way](https://snowfall.org/reference/lib/#external-overlays-and-modules).

Also, you might want to add some constraints on the structure of `systems.modules`, because currently the second (old) syntax just silently doesn't do anything instead of failing like it should.

**Comment by jakehamilton** [comment]
Oh boy, thank you for catching this!

**Comment by jakehamilton** [comment]
This should now be fixed!
