### ISSUE TITLE
Snowfall Lib looks very very promising 

### ISSUE THREAD

**Issue by c4milo** [snowfallorg/lib#27]
However, for Nix newbies like myself, it would be super useful to have examples we can quickly follow to get things started.

**Comment by aidenscott2016** [comment]
There are adequate examples in the quick-start guide. You can also refer to the author's personal config [here](https://github.com/jakehamilton/config/blob/main/flake.nix)

**Comment by jakehamilton** [comment]
Hey there!

As @aidenscott2016 mentioned, there are some examples in the quickstart and guides here: https://snowfall.org/guides/lib/quickstart/

Otherwise you could take a look at some of the templates that are available: https://github.com/snowfallorg/templates/
