### ISSUE TITLE
`nixpkgs.config.allowUnfree` is always `false`

### ISSUE THREAD

**Issue by tqwewe** [snowfallorg/lib#3]
I've created a flake for my OS configuration which I've pushed here https://github.com/tqwewe/config.

In my config, I've set `nixpkgs.config.allowUnfree = true;` in my config in my [system nix file](https://github.com/tqwewe/config/blob/main/systems/x86_64-linux/ari/default.nix#L87). Though when trying to install my flake, I get an error due to nvidia drivers being unfree:

```bash
[ari@ari:~/config]$ sudo nixos-rebuild build --flake .#
building the system configuration...
error: Package ‘nvidia-x11-520.56.06-5.15.93’ in /nix/store/csswjxkshhf3800f4vah9lx9j56hz3z3-source/pkgs/os-specific/linux/nvidia-x11/generic.nix:125 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "nvidia-x11"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```
And when inspecting in the repl, it shows that my flake has this value set to false.
```bash
[ari@ari:~/config]$ nix repl
Welcome to Nix 2.11.1. Type :? for help.

nix-repl> :lf .
Added 20 variables.

nix-repl> nixosConfigurations.ari.config.nixpkgs.config.allowUnfree
false
```

**Comment by jakehamilton** [comment]
In order to use unfree packages with the underlying flake-utils-plus channels, you'll need to allow it when you call mkFlake. Here is where I handle it in my flake: https://github.com/jakehamilton/config/blob/7975ae66c0c23296fb6c528641ab7db3236dbe9f/flake.nix#L124

**Comment by tqwewe** [comment]
Thanks! That seemed to solve it.
Is this specific to snowfall? Or is this flake-utils-plus? Also, a little unrelated, but I'm not sure how I can use unstable for specific packages only. I have [unstable defined as an input](https://github.com/tqwewe/config/blob/main/flake.nix#L6), though am not sure how I can use this in my system configuration for specific packages only.

**Comment by jakehamilton** [comment]
I think you want to create overlays that pull packages from the unstable channel. For example, to pull chromium from unstable: (this requires an `unstable` input on your flake)

https://github.com/jakehamilton/config/blob/main/overlays/chromium/default.nix

**Comment by jakehamilton** [comment]
I believe the reason you can't set allowUnfree in system module config is due to flake-utils-plus. It does some automatic configuration based on patched channels and their config.

**Comment by tqwewe** [comment]
Perfect thanks so much for your help!
