### ISSUE TITLE
Using flake parts

### ISSUE THREAD

**Issue by IogaMaster** [snowfallorg/lib#30]
How would I integrate flake parts with snowfall for a nixos config.

https://flake.parts/

**Comment by IogaMaster** [comment]
Nevermind, snowfall already does the things flake parts does

**Comment by bestlem** [comment]
However some nix tools seem only to work easily with flake-parts. Example are treefmt-nix. Also searching for config examples seems to show a lot of flake-parts.

There are blogs etc suggesting that flake-utils has issues and flake-parts is a better tool.

**Comment by TakodaS** [comment]
I found a way to use treefmt in snowfall-lib and posted it here: 
https://github.com/snowfallorg/lib/pull/131#issuecomment-2464423670
