### ISSUE TITLE
Issue migrating to v2, cannot find lib inside of system configuration file

### ISSUE THREAD

**Issue by dukeofcool199** [snowfallorg/lib#31]
I recently attempted to upgrade to snowfall-lib v2, but now when I try to build my systems I am met with the following error.

```
building the system configuration...
warning: Git tree '/home/jenkin/workspace/nix-configs' is dirty
error:
       … while calling the 'seq' builtin

         at /nix/store/3s69yxbbl116zwga3i6cy7prplywq0bn-source/lib/modules.nix:326:18:

          325|         options = checked options;
          326|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          327|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/3s69yxbbl116zwga3i6cy7prplywq0bn-source/lib/modules.nix:302:18:

          301|                     ''
          302|             else throw baseMsg
             |                  ^
          303|         else null;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: undefined variable 'enabled'

       at /nix/store/cc0c9nkgbvcbqgjzy6p68bvaj59md64i-22943hsd1bwsj4v1adilh6k1206h63a9-source/systems/x86_64-linux/jenktop/default.nix:60:16:

           59|     apps = {
           60|       ardour = enabled;
             |                ^
           61|       obs = enabled;
```

  I took a look at the migration guide, And I am not using anything that would have needed changing that was stated in the migration guide

here is a link to my configuration repo.

https://github.com/dukeofcool199/config/tree/master

any help would be greatly appreciated

**Comment by osv** [comment]
@dukeofcool199  You need move "modules/*" to "modules/nixos" 
I think this is not described in migration doc.

**Comment by jakehamilton** [comment]
@dukeofcool199 would you be able to push the broken version up to a different branch? I can take a look and see what's going wrong. The migration guide is likely missing some things.

**Comment by dukeofcool199** [comment]
@jakehamilton

https://github.com/dukeofcool199/config/tree/borked/attempt-to-migrate-to-v2

this branch has the snowfall-lib flake input updated to v2 and running `flake build-system jenktop` will showcase the issue

**Comment by jakehamilton** [comment]
@dukeofcool199 it looks like `enabled` comes from your library [here](https://github.com/dukeofcool199/config/blob/0084abeb9e150eae2720aa89834d9fc3ac6a17f0/lib/module/default.nix#L15), but is not in scope when used because internal libraries are now namespaced. See the [library quickstart](https://snowfall.org/guides/lib/library/) for an example.

By default, the library will be namespaced under `lib.internal`. This can be changed by setting `snowfall.namespace`: https://snowfall.org/reference/lib/#snowfall-configuration
