### ISSUE TITLE
homes.modules is not equivalent to setting a module for every home user

### ISSUE THREAD

**Issue by expipiplus1** [snowfallorg/lib#34]
I was a little surprised to find that these aren't equivalent (for a config with this single user and two hosts)

```
      homes.modules = with inputs;
        [ plasma-manager.homeManagerModules.plasma-manager ];
```

```
      homes.users."e@light-hope".modules = with inputs;
        [ plasma-manager.homeManagerModules.plasma-manager ];
      homes.users."e@howl".modules = with inputs;
        [ plasma-manager.homeManagerModules.plasma-manager ];
```

Notably in the former, the `plasma-manager` module is somehow sneaking into the system build (and causing problems because it's not compatible there).

(The latter only works because I'm `home-manager.users = lib.mkForce { };`ing in the system configs, it wasn't too clear to me how to use this "standalone" home manager that was talked about earlier this year)

**Comment by heinwol** [comment]
The same issue reproducible by me and I can say solution proposed by jakehamilton here works without breaking other functionality (at least at the first glance)

**Comment by jakehamilton** [comment]
Haven't gotten around to fixing this just yet, but it should be about as simple as I mentioned before. Will try and get to this soon...

**Comment by haraldh** [comment]
Can you elaborate on the workaround a little bit more (/me nix beginner), because I wasted a couple of hours trying ` homes.modules = ` before finding the workaround with `homes.users."foo@bar".modules` ... wish I had looked into this issue beforehand.

**Comment by haraldh** [comment]
Guess I would have to use a patched version of snowfall lib then

**Comment by heinwol** [comment]
@haraldh you can take a look at my fork

**Comment by haraldh** [comment]
Seems really simple as mentioned in https://github.com/snowfallorg/lib/issues/34#issuecomment-1833606811
```diff
@@ -332,19 +335,25 @@ in
                   users.${user-name} = mkAliasAndWrapDefinitions wrap-user-options options.snowfallorg.user;
 
                   # sharedModules = other-modules ++ optional config.snowfallorg.user.${user-name}.home.enable wrapped-user-module;
-                  sharedModules = other-modules ++ optional config.snowfallorg.user.${user-name}.home.enable user-module;
+                  sharedModules = # tracemsgN "SharedModules:" 4
+                    (other-modules
+                      ++ (optional config.snowfallorg.user.${user-name}.home.enable user-module)
+                      ++ (users.modules or [ ])
+                    )
+                  ;
                 };
               };
             }
```

**Comment by heinwol** [comment]
@haraldh and don't forget to remove this line at the end of the file

**Comment by jakehamilton** [comment]
@expipiplus1 I've updated the `dev` branch and this should now be working correctly. The only caveat is that you cannot set `home-manager.users.${user}.*` and must instead set `snowfallorg.user.${user}.home.config.*`.

**Comment by expipiplus1** [comment]
thanks!
