### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by noonien** [snowfallorg/lib#35]
I'm trying to define a `mkScript` helper function:
```
{ pkgs, lib, stdenvNoCC, makeWrapper, ... }:

{ pname, version, runtimeInputs ? [ ], src }:
stdenvNoCC.mkDerivation {
  inherit pname version src;
  nativeBuildInputs = [ makeWrapper ];

  phases = [ "installPhase" "fixupPhase" ];
  installPhase = ''
    install -Dm 555 $src $out/bin/${pname}
  '';
  postFixup = ''
    wrapProgram $out/bin/${pname} --prefix PATH : "${lib.makeBinPath runtimeInputs}"
  '';
  dontPatchELF = true;
}
```
I use it like so in some of my packages:
```
{ callPackage, pkgs, mkScript, ... }:
mkScript {
  pname = "wttr";
  version = "0.1";
  runtimeInputs = with pkgs; [ bash curl jq ];
  src = ./wttr;
}
```

Where should this helper go? In `lib` there is no implicit access to nixpkgs. ~~`overlays` does not seem to be evaluated before `packages`.~~ This isn't really a package, so maybe  it doesn't really make sense to have it in `packages` anyway, even though this is how nixpkgs does it. However, putting it in `packages` causes an infinite recursion when trying to use it from other packages.

What are your opinions on this?

**Comment by jakehamilton** [comment]
This is currently a very grey area for Nix Flakes since functions like this are not valid in the packages output, but are also cumbersome to place in lib. My suggestion would be to do one of the following:

- Use NixPkgs builders like mkShellScriptBin or mkShellApplication instead.
- Put this function in lib and accept a pkgs argument.
- Put this in an overlay.

**Comment by noonien** [comment]
I've ended up putting it in an overlay, but I'm not sure how the points above are addressed by this solution. The function is still exported as a package in the overlay, just not at the flake level.

The `nixpkgs` flake does export these functions as the flake output btw, for example:
```shell
$ nix run nixpkgs#writeShellScript
error: attribute 'legacyPackages.x86_64-linux.writeShellScript.type' does not exist
```
While this errors, it does not error because the package is missing.
Just posting this as a data sample, I'm also not a very big fan of this approach, but I'm not sure I dislike it more than having an overlay.
