### ISSUE TITLE
No namespace

### ISSUE THREAD

**Issue by noonien** [snowfallorg/lib#36]
Is it possible for packages to not be namespaced?

Namespacing doesn't provide my setup with any additional benefit, however, it does make package interdependencies more cumbersome.

I've tried solving this with an overlay:
```
_: _: prev: prev.my-namespace
```
However, `overlays` does not seem to be evaluated before `packages`, so this does not work. At least not when trying to run packages directly from `nix`, I've not tested building entire systems yet.

**Comment by noonien** [comment]
It seems I was wrong, `overlays` do seem to be evaluated before `packages`. Using the above overlay works just fine.

**Comment by jakehamilton** [comment]
The namespace feature is necessary to avoid naming conflicts with the rest of the package set and to allow for lazy evaluation of your flake's packages. Snowfall Lib originally did not have this feature and there were a whole host of issues that would occur. At least for now the best strategy going forward is to build with a flake namespace in mind.

**Comment by noonien** [comment]
While I'm sure this is a sensible solution for snowfall, I've never had issues in the past with overlying packages without a namespace in my config.

It would be extremely helpful to have the option to disable namespaces at least.

I've tried emulating this behavior by creating an overlay to import all my packages, however, I can't seem to get a version to work that automatically imports all packages, I have to specify all of them manually.

**Comment by jakehamilton** [comment]
If you're able to resolve the issues with infinite recursion and name collisions then I'd be happy to review a PR 👍
