### ISSUE TITLE
Install internal package?

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/lib#42]
I am unable to figure out how to install one of my internal packages.

I set packages-namespace to "united" and tried

```
environment.systemPackages = with pkgs; [
  united.hitman-woa
];
```

And I got `error: attribute 'hitman-woa' missing`. 

(This is using the legendary builder from nixos-gaming, but I don't think that matters.)

I tried dropping the package-namespace and doing "internal.hitman-woa" and it said it couldn't find "internal" either. If I understand the documentation properly, I should be able to install this package as pkgs.united.hitman-woa but it isn't working.

**Comment by jakehamilton** [comment]
Can you share your whole flake in a GitHub repo?

**Comment by YaroKasear** [comment]
> Can you share your whole flake in a GitHub repo?

Sure thing: 

[The United Flake](https://github.com/YaroKasear/flakes)

I worked on a bunch of other things, so I had removed it for a while, I tried again to install it in systems/x84_64-linux/loki/default.nix. At this point I'm not concerned if the package itself builds successfully yet, but I want to get it to the point it'll try to. Hard to do when my flake apparently can't tell my package nix file is there. Or something.

**Comment by jakehamilton** [comment]
It looks like your package isn't producing a derivation: https://github.com/YaroKasear/flakes/blob/main/packages/hitman-woa/default.nix

Rather, it seems like you may have meant for this to be a module or in your system config?

**Comment by YaroKasear** [comment]
> It looks like your package isn't producing a derivation: https://github.com/YaroKasear/flakes/blob/main/packages/hitman-woa/default.nix
> 
> Rather, it seems like you may have meant for this to be a module or in your system config?

Hmm, that's odd. I guess I just assumed that the legendary builder provided by nixos-gaming would produce a derivation. That's pretty standard for builders, no?

I'll just make it a module. No need for a package, really.

**Comment by YaroKasear** [comment]
Is it okay to reopen this? 

I'm trying to make a different package and still unable to get the package to show up. I'm using mkDerivation and repl is even showing it under "packages.x86_64." But putting "united.protomuck" in there just gives me "undefined variable 'united'".

Looking at your config makes it look like this should work that way so I'm feeling a little confused why it isn't. Can you give me an idea of how I'm supposed to do packages correctly with snowfall-lib?

**Comment by YaroKasear** [comment]
Okay, I was able to install but only as a system package. It seems like homes can't see the packages.

How can I install my own package using home-manager in snowfall-lib?

**Comment by jakehamilton** [comment]
Ah this is indeed a bug, I need to dig into this. I'll try and use your config as an example. If you could keep a branch up that reproduces the behavior that would be extremely helpful!

**Comment by YaroKasear** [comment]
> Ah this is indeed a bug, I need to dig into this. I'll try and use your config as an example. If you could keep a branch up that reproduces the behavior that would be extremely helpful!

Made a branch https://github.com/YaroKasear/flakes/tree/home-manager-package-bug

**Comment by jakehamilton** [comment]
@YaroKasear can you make sure you are setting useGlobalPkgs?

https://github.com/snowfallorg/lib/pull/47

**Comment by YaroKasear** [comment]
> @YaroKasear can you make sure you are setting useGlobalPkgs?
> 
> #47

I am unclear where to set this.

**Comment by YaroKasear** [comment]
Unfortunately, setting useGlobalPkgs did not work:

```
error:
       … while calling the 'head' builtin

         at /nix/store/qn2bp2ipwdfsv5a4fp8sdk6kmibxhvsw-source/lib/attrsets.nix:960:11:

          959|         || pred here (elemAt values 1) (head values) then
          960|           head values
             |           ^
          961|         else

       … while evaluating the attribute 'value'

         at /nix/store/qn2bp2ipwdfsv5a4fp8sdk6kmibxhvsw-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'united' missing

       at /nix/store/if94dkxcrg1z6vqmwzi6ilynyh0yc9bh-62lc7nnbh4xmb85x0jpsaabk6z4r2jxl-source/homes/x86_64-linux/yaro@loki/default.nix:14:21:

           13|
           14|   home.packages = [ pkgs.united.protomuck ];
             |                     ^
           15| }
       Did you mean one of unit, units, untex or unused?
```

**Comment by jakehamilton** [comment]
@YaroKasear it looks like on that branch you haven't set `home-manager.useGlobalPkgs = true;` in your system configuration. Adding it to your NixOS config should do the trick. Try putting it in `systems/x86_64-linux/loki/default.nix`. The option comes from the Home-Manager NixOS module: https://nix-community.github.io/home-manager/nixos-options.xhtml#nixos-opt-home-manager.useGlobalPkgs

**Comment by YaroKasear** [comment]
That seems to have worked. 

By the way, do you have Discord for Snowfall? It might be better for me to ask questions there instead of filing issues here.

**Comment by pinkcreeper100** [comment]
@jakehamilton what if (due to vlinkz merging snowflakeos into this gh org) that discord server were to be rebranded for both that and snowfall

**Comment by pinkcreeper100** [comment]
true
