### ISSUE TITLE
Howto pass down global variables?

### ISSUE THREAD

**Issue by jhartma** [snowfallorg/lib#43]
This may be a stupid question, but I cannot figure out how to pass global variables defined in flake.nix. E.g. I want to have a specific theme for a host and pass it to the system configuration as well as the home-manager config. I tried specialArgs, but I cannot figure out how to access the attribute. Usually, I had something like this in my nix files:
```nix 
{
    pkgs,
    theme,  # specialArg
    ...
}: {
...
}

```
but that says the attribute cannot be found. What would be the recommended way to do this?

**Comment by jakehamilton** [comment]
Ah that is indeed a typo, sorry about that! Looks like the other examples on that page got the wording right but I must have misspelled the last one. Oops. Thank you for reporting this 🙏

**Comment by jakehamilton** [comment]
I've updated the docs site and it will be deployed shortly. Thanks again for creating this issue!
