### ISSUE TITLE
Snowfall news hard to find in the winter

### ISSUE THREAD

**Issue by canadaduane** [snowfallorg/lib#45]
It's difficult to discover what progress has been made on this project during the winter.

![image](https://github.com/snowfallorg/lib/assets/129/9c5cee35-b995-4471-9e49-d4b7a25a9969)

**Comment by pinkcreeper100** [comment]
look for the hashtag `#SnowfallLib`

**Comment by jakehamilton** [comment]
Ha! You can expect every Snowfall Lib post to use `#SnowfallLib`. If changes are substantial or more frequent and warrant lots of updates then you can expect the website (snowfall.org) to mention it 👍

**Comment by jakehamilton** [comment]
Going to close this issue. We may come up with a central place for news in the future, but for now the above solutions are good enough.
