### ISSUE TITLE
Missing documentation for included modules

### ISSUE THREAD

**Issue by LovingMelody** [snowfallorg/lib#53]
Unable to find any documentation for the `user` module, it appears to be missing other than mentions in the issues and migration guide. Reference on how to use this and its intended use case (unable to tell if this is meant to replace defining the user in `users.users`). The module should be properly documented with examples.

**Comment by jakehamilton** [comment]
Hey there! I agree. There hasn't been a need for people to use the included modules prior to the upcoming v3. With those changes it will be necessary to use at least the system module for specifying home-manager config.

**Comment by jakehamilton** [comment]
To answer the included question @LovingMelody, this does not replace `users.users`. Instead it is for configuration of Snowfall Lib integration and in v3 will be necessary for configuring home-manager user options.

**Comment by bestlem** [comment]
I just spent time looking at your config and seeing modules/home/default.nix and it not appearing in your suites to enable it.

I eventually found the hard coding in the library.

If this is a special fn what should be in there.

**Comment by jakehamilton** [comment]
@bestlem I believe this is covered in the docs: https://snowfall.org/reference/lib/#flake-structure

**Comment by bestlem** [comment]
@jakehamilton Not as far as I can see. That section says that a module called user for home-manager would be defined in home/user/default.nix, but it does not say that that file is always loaded. by function snowfall-user-home-module and not bu the usual share-*.modules.

Why is this loaded differently? and what should be in it.

**Comment by jakehamilton** [comment]
@bestlem all modules are always added. That means `modules/nixos` entries are included in NixOS systems, `modules/home` are included in home-manager configurations, and `modules/darwin` are included for macOS.

**Comment by jakehamilton** [comment]
With the release of v3, the docs have been updated to include information about both the system options and home options available:

https://snowfall.org/guides/lib/systems/

https://snowfall.org/guides/lib/homes/
