### ISSUE TITLE
Specify specific nixpkgs for an output?

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/lib#54]
I've been thinking since I'm using this flake on both desktop and server systems, it'd be really nice to be able to pass different pkgs/nixpkgs to different configs. Is this possible?

For example, my loki system would be using nixpkgs-unstable, but I might want my servers to stick with nixos-23.11. Does snowfall-lib provide me a way to do this?

**Comment by DarkKronicle** [comment]
I think this *may* actually be possible currently.

There's no easy way to access it directly, but you could use [this](https://github.com/snowfallorg/lib/blob/92803a029b5314d4436a8d9311d8707b71d9f0b6/snowfall-lib/system/default.nix#L235) argument. 

(Not tested) but I think this may work:
```nix
inputs = {
	nixpkgs = "...23.11";
	nixpkgs-unstable = "...unstable";
};

outputs = inputs:
      inputs.snowfall-lib.mkFlake {
    		...
			systems.hosts.<my-host>.channel = "nixpkgs-unstable";
	  }
```

**Comment by DarkKronicle** [comment]
Here are the problems I've found that default to nixpkgs:
- [flake create-packages](https://github.com/snowfallorg/lib/blob/92803a029b5314d4436a8d9311d8707b71d9f0b6/snowfall-lib/flake/default.nix#L141). When calling create-packages, the default is just `nixpkgs`.
- Potential whenever snowfall uses `user-inputs.self.pkgs`, but I'm not entirely sure where `self.pkgs` is coming from

Anyways, from what I can tell, setting the channel manually works. The only issue is custom packages will default to `nixpkgs` and maybe overlays as well. @YaroKasear

**Comment by jakehamilton** [comment]
This may be reconsidered in the future, but for now Snowfall Lib is going to remain as-is using a primary channel (nixpkgs) to function.
