### ISSUE TITLE
Building a hyperVConfiguration fails. 

### ISSUE THREAD

**Issue by LovingMelody** [snowfallorg/lib#55]
When attempting to create a live ISO using a system located in `systems/x86_64-install-iso-hyperv/installer` the build fails
Error:
```console
error:
       … while evaluating the attribute 'config.system.build."${(image).config.formatAttr}"'

         at /nix/store/mz7drsiaggcysnd5b82hlpky3nd981z9-source/lib/modules.nix:322:9:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          323|         _module = checked (config._module);

       … while calling the 'seq' builtin

         at /nix/store/mz7drsiaggcysnd5b82hlpky3nd981z9-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'x86_64-install-iso-linux' missing

       at /nix/store/94gag39fil45c81x34rragrb3radkhyh-source/lib/mkFlake.nix:83:25:

           82|
           83|   getChannels = system: self.pkgs.${system};
             |                         ^
           84|   getNixpkgs = host: (getChannels host.system).${host.channelName};
           ```

**Comment by jakehamilton** [comment]
Ah, thank you for catching this. I have pushed a fix to the `dev` branch. Could you try updating the flake input and then building?

**Comment by LovingMelody** [comment]
Looks like it's building but doesn't seem to boot

**Comment by LovingMelody** [comment]
Unsure why this isn't working assuming this is using `nixos-generators` on the back-end. Moving the system from `systems/x86_64-install-iso-hyperv/installer` to `systems/x86_64-linux/installer` then running `nix build .#nixosConfigurations.installer.config.formats.install-iso-hyperv` creates a working image.

**Comment by jakehamilton** [comment]
@LovingMelody I don't have a hyperv setup to test with so I can't help with debugging the boot issue, but I would imagine at that point it is either down to a configuration of `nixos-generators` or the system config. I don't see any actual differences in the `nixos-generators` usage or the `nixpkgs` input compared to your main branch, so I would imagine there is a difference in the system configuration. I do see that `modules/nixos/defaults/default.nix` is enabled by default and specifies `boot.initrd.systemd.enable`. Perhaps a different boot setup is needed for hyperv?

**Comment by LovingMelody** [comment]
Thanks, for checking, I will look into my configuration further. For future reference, you are able to boot ISO files with following command even the hyperv one `qemu-system-x86_64 -boot d -cdrom PATH_TO_ISO`
