### ISSUE TITLE
Module File naming

### ISSUE THREAD

**Issue by bestlem** [snowfallorg/lib#57]
All modules, shells, hosts etc are directories with a default.nix in them.

It would be a nice thing for module <x> that as well as having `<x>/default.nix` you could have `x.nix` instead. For complex things you need the first case but for other e.g. where you are just enabling a program it would make navigation by Finder or other file managers easier as there would be less need to expand nodes in the tree and also the file names in your editor would not all be default.nix and so easier to tell apart.

This is done in other nix packages, e.g. rakeLeaves from several including digga.

**Comment by jakehamilton** [comment]
The `default.nix` convention allows for extracting things like types or shared values into other co-located Nix files. Snowfall Lib originally picked up any Nix file, but it quickly became clear that there are files that should not be collected.

**Comment by bestlem** [comment]
I agree that the current setup is needed but I was asking that the filename.nix style would be allowed as well and not instead of.

I don't see how you would pick up unwanted files - if done as rake leaves does - if there is a default.nix in a directory just load that file but if no default.nix then load *.nix
