### ISSUE TITLE
modules common to both nixos and darwin?

### ISSUE THREAD

**Issue by devzero** [snowfallorg/lib#59]
What is the idiomatic or preferred way to specify modules that are common to both darwin and nixos systems?  Many of the configuration settings (at least on my flakes) are the same on both platforms.  Should I make a common directory next to nixos and add includes = [../../common/default.nix]; in both directories?  I tried modules/nixos/ -> ../common/ but that symlinked directory didn't appear to be visible in the built configuration.  I would rather not maintain two copies.

**Comment by jakehamilton** [comment]
This has been a tough problem. There are enough differences between NixOS and Nix Darwin that providing a shared module isn't typically a good idea. But for custom things within your own config there ends up being a lot of similar settings. I think for now the solution would be to make separate common modules and import them into your systems manually. You can do so using paths, but it is also possible to use some of the fs helpers in snowfall lib to glob all your shared modules.
