### ISSUE TITLE
Accessing other system configs?

### ISSUE THREAD

**Issue by usmcamp0811** [snowfallorg/lib#62]
I'm probably just being dumb, but can you provide an example of how to reference another system config? What I want to do is get a list of systems that have a particular service enabled and then use that in a proxy config. I thought I would be able to do something like 

```                                                                                                  
sys-names = builtins.attrNames self.nixosConfigurations;                                                            
searxEnabledSystems = builtins.filter (computer: self.nixosConfigurations.${computer}.config.services.searx.enable == true) sys-names; 
```

but I just get errors that tell me: `error: attribute 'self' missing` 

TIA!

**Comment by jakehamilton** [comment]
Heya! You can access your flake via the `inputs` argument in your modules. So you would do:

```nix
{ inputs }:
let
  configs = inputs.self.nixosConfigurations;
in
{
  # Do something with configs...
}
```
