### ISSUE TITLE
Templates don't have a description field which breaks `nix flake show`

### ISSUE THREAD

**Issue by msfjarvis** [snowfallorg/lib#63]
Compare the auto-generated `templates` output from `snowfallorg/lib`:

<details>
<summary>Details</summary>

```json5
# nix eval github:msfjarvis/dotfiles#templates --json | jq .
{
  "cpp": {
    "path": "/nix/store/clx87162mg3fk6ryf23cifqnz3904pnr-3bh3fcin9s2nq73mnqwxj8lsh60hgxwr-source/templates/cpp"
  },
  "go": {
    "path": "/nix/store/clx87162mg3fk6ryf23cifqnz3904pnr-3bh3fcin9s2nq73mnqwxj8lsh60hgxwr-source/templates/go"
  },
  "node": {
    "path": "/nix/store/clx87162mg3fk6ryf23cifqnz3904pnr-3bh3fcin9s2nq73mnqwxj8lsh60hgxwr-source/templates/node"
  },
  "python": {
    "path": "/nix/store/clx87162mg3fk6ryf23cifqnz3904pnr-3bh3fcin9s2nq73mnqwxj8lsh60hgxwr-source/templates/python"
  },
  "rust": {
    "path": "/nix/store/clx87162mg3fk6ryf23cifqnz3904pnr-3bh3fcin9s2nq73mnqwxj8lsh60hgxwr-source/templates/rust"
  }
}
```

</details>

with one hand-written, for example in [home-manager](https://github.com/nix-community/home-manager):

<details>
<summary>Details</summary>

```json5
# nix eval github:nix-community/home-manager#templates --json | jq .
{
  "nix-darwin": {
    "description": "Home Manager as a nix-darwin module,",
    "path": "/nix/store/gmmz689vqa0m8z11x4184ckcb365fqf2-source/templates/nix-darwin"
  },
  "nixos": {
    "description": "Home Manager as a NixOS module,",
    "path": "/nix/store/gmmz689vqa0m8z11x4184ckcb365fqf2-source/templates/nixos"
  },
  "standalone": {
    "description": "Standalone setup",
    "path": "/nix/store/gmmz689vqa0m8z11x4184ckcb365fqf2-source/templates/standalone"
  }
}
```

</details>

This isn't _too_ much of a deal-breaker but it'd be nice if there was a way to make it work.

**Comment by msfjarvis** [comment]
> Ah this is under-documented. You can set `templates.<name>.description` in your call to mkFlake. Similar to other overrides, any values passed to `templates.<name>.*` will be applied to the output.

Oh nice, thanks! I looked through the guide on snowfall.org and didn't find a templates section. I'll leave the issue open if you wanna keep it open to track adding some docs.

**Comment by msfjarvis** [comment]
I added the descriptions like this: https://msfjarvis.dev/g/dotfiles/0601cc7f19e8
but that caused the `path` attribute to disappear from the output which fully breaks `nix flake init`. Is there something I'm missing with regards to attribute merging?

```json5
# nix eval .#templates --json | jq .
{
  "cpp": {
    "description": "devshell for a C++ project"
  },
  "go": {
    "description": "devshell for a Golang project"
  },
  "node": {
    "description": "devshell for a NodeJS project"
  },
  "python": {
    "description": "devshell for a Python project"
  },
  "rust": {
    "description": "package definition and devshell for my-rust-package"
  }
}
```

**Comment by jakehamilton** [comment]
Hmm that's not what should be happening. Seems like a bug, I'll take a look.

**Comment by msfjarvis** [comment]
I also had an issue with the `packages` output being broken when I tried to set a custom one like so: `packages.aarch64-darwin.macbook = inputs.self.darwinConfigurations.Harshs-MacBook-Pro.system;`. Maybe these are related?

**Comment by jakehamilton** [comment]
@msfjarvis for that use case you'll want to use `outputs-builder`.

**Comment by jakehamilton** [comment]
Ah, figured this out. Including a fix in the next push to `dev` :+1:

**Comment by jakehamilton** [comment]
Snowfall Lib v3 now includes a fix for this and I've updated the docs to explain how to include descriptions:

https://snowfall.org/guides/lib/templates/

**Comment by TakodaS** [comment]
Would automatically getting the description from the flake.nix file under `./templates/my-template/` be feasible and/or desirable?
