### ISSUE TITLE
bug: weird error can track it down

### ISSUE THREAD

**Issue by xiro-codes** [snowfallorg/lib#64]
[output](https://app.warp.dev/block/9NNTk1AcKt2tDsGBFSbo0T)

this happens each time i run rebuild

**Comment by pinkcreeper100** [comment]
@xiro-codes would you be able to share your config?

**Comment by xiro-codes** [comment]
git@github.com:xiro-codes/dotfiles.v2.nix.git

**Comment by xiro-codes** [comment]
I did fix it by upgrading to the dev branch of lib

**Comment by pinkcreeper100** [comment]
yeah i would recommend staying on `dev` for now, maybe at least until v3
