### ISSUE TITLE
Finds libs in /lib rather than /snowfall-root/lib

### ISSUE THREAD

**Issue by iwanb** [snowfallorg/lib#66]
When using a custom snowfall root directory, the libs from the lib subdirectory are not added. Rather it looks at the lib directory directly under the flake.nix file.

I created an example repo, modified from the template:
https://github.com/iwanb/snowlib-example

```
$ nix eval .#lib
{ }
```

**Comment by jakehamilton** [comment]
Ah this is definitely a bug, thank you for finding it!

**Comment by jakehamilton** [comment]
Fixed in v3!
