### ISSUE TITLE
Types of fs.get-snowfall-file

### ISSUE THREAD

**Issue by bestlem** [snowfallorg/lib#69]
I am using dev branch.

In the documentation and code the entry for 
` ## Get a file path relative to the user's snowfall directory.
    ## Example Usage:
    ## ```nix
    ## get-snowfall-file "systems"
    ## ```
    ## Result:
    ## ```nix
    ## "/user-source/snowfall-dir/systems"
    ## ```
    #@ Path -> Path
   
So this should return a Path.

However in nix real I see
```
nix-repl> :t inputs.snowfall-lib._snowfall.internal-lib.fs.get-snowfall-file "systems"
a string with context

nix-repl>  inputs.snowfall-lib._snowfall.internal-lib.fs.get-snowfall-file "systems"
"/nix/store/504ckvv0yz7nwa710byrvx6cqxhvq0i3-n9zrfv8j9s22qfyvm48bblzvak6phy32-source/systems"
```

So returns a String,
Is this just a documentation error or am I misusing this.

I also not that it returns the full nix store path and not the example you show.

I was trying to debug some of my own code that was getting an error consistent with this.

**Comment by jakehamilton** [comment]
What error were you getting? Can you share a minimal reproduction?

**Comment by bestlem** [comment]
I don't have a minimal example, it was in a library. The nix interpreter complained that it was expecting a Path and got a String. The /nix/store/uid-like is from the snowfallorg call.
```
error: lib.fileset.toList: Argument ("/nix/store/ac7mvd8vjpgpkacg2fabcmf8nybmhgn6-annc0dfmhcpcp62yv1gl2ci8264mrlxl-source/profiles/home/fish") is a string-like value, but it should be a file set or a path instead.
```

The nix repl examples are in effect a minimal reproducible example as they show the error as it finds the wrong type. This is explicit 
```
nix-repl> builtins.isPath (inputs.snowfall-lib._snowfall.internal-lib.fs.get-snowfall-file "systems")
false
```

**Comment by jakehamilton** [comment]
I see. I think the type here is the problem, it should be communicating that the return type is "String with context". For some reason I had thought that this was compatible with path types, but it looks like you'll need to call `builtins.toPath` on the returned value.

**Comment by bestlem** [comment]
I agree - the documentation is incorrect. (Unfortunately my use case would have liked paths - but that is my problem)

I would note that builtins.toPath is depreciated Use ./. + string instead or similar
But as your function returns a path in nix store all these fail.

I managed to work around as putting my function in the .mix file it was used rather than in the lib meant I did not need to find the path and just used relative paths.
It would be nice if there  were functions of yours that returned paths in the flake not in nix store but that is a new feature  and as I note I don't need it now.

Thanks for your responses.

**Comment by jakehamilton** [comment]
Ah, I didn't realize that function was being deprecated. I think Snowfall Lib can swap out the string interpolation with concatenation. I think that should retain the type.

**Comment by jakehamilton** [comment]
I've updated this in v3, should be taken care of now!

**Comment by jakehamilton** [comment]
Heads up, depending on how things go this may be reverted due to causing issues with child paths trying to refer to ancestors using Nix paths.
