### ISSUE TITLE
Feature: Standalone Home-Manager

### ISSUE THREAD

**Issue by EdenEast** [snowfallorg/lib#7]
First off I would just like to say great work on this nix configuration framework. This is a great resource for people trying to create their own nix flake configurations.

I have wanted to see if I can implement my configuration [[nyx](https://github.com/edeneast/nyx)]. One use case that I found I was not able to replicate is creating a [standalone](https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone) `Home-Manager` output. My configuration contains multiple computers as well as a generic home manager configuration for when I have to use windows and I use wsl.

It would be nice to have the same use case as nix-darwin but for home manager.

**Comment by jakehamilton** [comment]
Hey @EdenEast! I'm glad Snowfall Lib is helpful (even if it's missing a feature currently). I'm out of commission at the moment due to some health issues but I was actually working on exactly this feature. It's looking like the next version of Snowfall Lib will be including support for homeModules as well as homeConfigurations. Still some things to work out and it'll have to wait until I'm doing better, but I plan on getting to it 😄

**Comment by EdenEast** [comment]
Sorry to hear that you are having health issues and hope it is resolved soon. Do you have a idea what this would look like, I would be interested in helping with this effort.

**Comment by nkprince007** [comment]
@jakehamilton Hope you get well soon. Great work, man! I've really been looking forward to a solid home-manager integration.

**Comment by khaneliman** [comment]
Is this work necessary to supporting importing home manager modules? I'm still learning nix and see examples of people using homeModule imports but haven't been able to get it to work in my config based on jake's.

**Comment by jakehamilton** [comment]
Hi @khaneliman 👋

This would make it easy to use Home Manager with Snowfall Lib, but you can do so without this integration. To support standalone Home Manager today you can set `homeConfigurations` on your flake outputs. For example:

```
inputs.snowfall-lib.mkFlake {
  inherit inputs;
  src = ./.;

  homeConfigurations = {
    "user@system" = inputs.home-manager.lib.homeManagerConfiguration {
      modules = [ ./home.nix ];
      pkgs = inputs.nixpkgs.legacyPackages.x86_64-linux;
    };
  };
}
```

**Comment by Animeshz** [comment]
Hey @jakehamilton, first of all a thanks for this library, really helps to work on configs around a standard folder structure.

There's also https://github.com/numtide/system-manager coming up!

From your last comment I think I deduce that its possible to accommodate any of that future comings (or even custom derivations from lib/) while still maintaining a defined folder structure given by this library.

Though can you please generify the folder structure? My proposed changes:

```
flake-root/
├─ flake.nix                [flake]
├─ lib/
│  ├─ default.nix           { lib, inputs, snowfall-inputs }: {}
│  └─ **/
│     └─ default.nix        { lib, inputs, snowfall-inputs }: {}
├─ packages/
│  └─ **/
│     └─ default.nix        { lib, ... }@pkgs: {}
├─ overlays/
│  └─ **/
│     └─ default.nix        { channels, ... }: final: prev: {}
│
| (NOTE: actual changes below, more specifically, everything one-level down)
|
├─ modules/
│  └─ <nixos|systems|homes|anything|...>/
│     └─ <module-name>/
│        └─ default.nix     { options, config, pkgs, lib, ... }@inputs: {}
└─ configs/
   └─ <nixos|systems|homes|anything|...>/
      └─ <architecture>-<format>/
         └─ <config-name>/
            └─ default.nix  { config, pkgs, lib, modulesPath, ... }@inputs: {}
```

The `snowfall-lib.mkLib` shall take configs from `configs/a/**` and allow the access of all the modules from `modules/a/**`, hence an easy and consistent behavior.

**Comment by Animeshz** [comment]
> Hi @khaneliman wave
> 
> This would make it easy to use Home Manager with Snowfall Lib, but you can do so without this integration. To support standalone Home Manager today you can set `homeConfigurations` on your flake outputs. For example:
> 
> ```nix
> inputs.snowfall-lib.mkFlake {
>   inherit inputs;
>   src = ./.;
> 
>   homeConfigurations = {
>     "user@system" = inputs.home-manager.lib.homeManagerConfiguration {
>       modules = [ ./home.nix ];
>       pkgs = inputs.nixpkgs.legacyPackages.x86_64-linux;
>     };
>   };
> }
> ```

@jakehamilton One more thing I noticed is that, this passes `lib` parameter to `./home.nix`, without merging the lib present at `./lib`, is it a bug?

**Comment by khaneliman** [comment]
@jakehamilton should this be closed as its in dev now? or you waiting for it to go to main/master?

**Comment by jakehamilton** [comment]
Hey there folks! This should all now be taken care of in the dev branch, but I will be leaving this issue open until it is fully released 👍

@Animeshz apologies for not replying sooner! The method mentioned there works outside of Snowfall Lib so you wouldn't have access to many of the niceties it provides. You should now be able to switch to the dev branch and use the built-in support for `homes/` instead!

**Comment by jakehamilton** [comment]
That's it folks! We're officially on v2, Home Manager support is here!

**Comment by Cybolic** [comment]
Sorry for posting on a completed issue, but I can't find any information about what explicitly enables or disables a stand-alone home-manager setup. In my current flake (using the `dev` branch to not break on my home manager modules), it seems the default is to build any home-manager config as a NixOS module if a `homes/...` directory is found, and I can't seems to find any way to turn this off.
Can anyone point me at an example of a standalone home-manager installation?

**Comment by jakehamilton** [comment]
@Cybolic when v3 is released I will have proper docs for this, but the answer is that if you want to use NixOS but do not want home-manager set up for your user via NixOS then you will want to set `snowfallorg.users.<name>.home.enable = false`.

https://github.com/snowfallorg/lib/blob/91ab40c2e01cc1bade8092604370964ee86e9317/modules/nixos/user/default.nix#L65
