### ISSUE TITLE
accessing home-manager user options in system configuration

### ISSUE THREAD

**Issue by danknil** [snowfallorg/lib#70]
i want to be able to access configuration of my user to create users automatically and to enable certain features (e.g. enable hyprland system-wide if at least 1 user have it enabled to be able to access hyprland through display manager)
example: https://pastebin.com/fAKR7fQ0

**Comment by pinkcreeper100** [comment]
create a module and use `lib.mkDefault` to set it to true

**Comment by jakehamilton** [comment]
Hey there!

The v3 of Snowfall Lib (currently on the `dev` branch) supports automatically creating users based on `homes/` configurations if that helps with part of this.

As for checking whether a user has a certain setting enabled in their home configuration you can reference the value from a NixOS module as `config.home-manager.users.<name>`. With that you should be able to access the resolved configuration.

**Comment by jakehamilton** [comment]
Closing this issue now that v3 is out and everything here should be doable. If there's still an issue feel free to reopen :)
