### ISSUE TITLE
setting `channels-config.allowUnfree` doesn't seem to allow usage with the nix cli

### ISSUE THREAD

**Issue by pinkcreeper100** [snowfallorg/lib#72]
i have it set here: https://git.gay/pinkcreeper100/nix-config/src/branch/main/flake.nix#L41

but i am still unable to use unfree packages with `nix run` or `nix shell`

example:
![image](https://github.com/snowfallorg/lib/assets/35699052/2fa767a7-4686-4545-88aa-d553f51ccbd4)

**Comment by jakehamilton** [comment]
This is a limitation of Nix flakes. When running `nix run nixpkgs#...` you are referring to the nixpkgs flake directly and not the package set used for your system. If you want to work around this you can either:

1. Use `--impure` with one of the listed workarounds from the cli message.

2. Replace `nixpkgs` in the call to `nix run` with something like `self.pkgs.nixpkgs.x86_64-linux.some-package`.

**Comment by jakehamilton** [comment]
Going to close this since it isn't Snowfall Lib related.
