### ISSUE TITLE
Strange problem building home-manager configuration standalone.

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/lib#76]
I'm not sure this is actually an issue with snowfall-lib, but I can't find any information on this issue anywhere, so I might use this as a starting point. I am trying to update my home-manager deployment on one of my servers and I'm getting the below error I can't figure out where it's coming from:

```error: nixVersions.unstable has been removed. For bleeding edge (Nix master, roughly weekly updated) use nixVersions.git, otherwise use nixVersions.latest.```

Google's given me zero helpful results, I tried to grep through my Nix store to see what has this error... and found nothing. 

I'll understand if you don't want me to start here with finding the issue, but I imagine this is potentially somewhere in home-manager and I use home-manager configs through snowfall-lib. 

Is anyone else having this problem or had this problem and fixed it? If so, how?

I made a branch of my flake: https://github.com/YaroKasear/flakes/tree/nixVersions.unstable-has-been-removed

**Comment by YaroKasear** [comment]
As an update, apparently this is caused by a nixpkgs update:

https://github.com/NixOS/nixpkgs/commit/2b4e18f3d4a7b80af21b640c0970f83b34efceff

I don't set nix-package in my flake, so this may be triggered somewhere in snowfall-lib or in one of its libraries, I think.

**Comment by YaroKasear** [comment]
Setting nix.package = pkgs.nixVersions.latest explicit;y in the flake seems to work.

**Comment by jakehamilton** [comment]
It may have been caused by this line:

https://github.com/YaroKasear/flakes/blob/nixVersions.unstable-has-been-removed/modules/nixos/common/default.nix#L59

**Comment by YaroKasear** [comment]
> It may have been caused by this line:
> 
> https://github.com/YaroKasear/flakes/blob/nixVersions.unstable-has-been-removed/modules/nixos/common/default.nix#L59

I tried commenting that out (Along with my fix above.) and still got the error, unfortunately.

**Comment by bestlem** [comment]
It is caused by flake-utils-plus calling nixUnstable https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/145 There is a PR from https://github.com/fl42v/flake-utils-plus/tree/master 9so I expect changing flake-utils-plus.urt to github:fl42v/flake-utils-plus should work.

I did the nix.package = pkgs.nixVersions.latest  but did not seem to be sufficient.

**Comment by YaroKasear** [comment]
> It is caused by flake-utils-plus calling nixUnstable [gytis-ivaskevicius/flake-utils-plus#145](https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/145) There is a PR from https://github.com/fl42v/flake-utils-plus/tree/master 9so I expect changing flake-utils-plus.urt to github:fl42v/flake-utils-plus should work.
> 
> I did the nix.package = pkgs.nixVersions.latest but did not seem to be sufficient.

You do awesome work! I'll keep my little "hack" in place until the PR is ready.

**Comment by bestlem** [comment]
@YaroKasear - I think you might need the hack in future (or even remove that line completely. I had to do that and the change in url. I think probably best if this issue was kept open until flake-util-plus is fixed so the issue is more easily found.

I have now done the updayte to my flake and done minimal tests
```
flake-utils-plus = {
      # url = "github:gytis-ivaskevicius/flake-utils-plus";
      url = "github:fl42v/flake-utils-plus";
      inputs.flake-utils.follows = "flake-utils";
    };
```

**Comment by bestlem** [comment]
flake-utils-plus has now merged the patch
