### ISSUE TITLE
Pass `src` as an argument to modules

### ISSUE THREAD

**Issue by songpola** [snowfallorg/lib#78]
It would be great to be able to access snowfall's `src` (or `root`) within a module.

**Example**
```nix
# $HOME/nixos-config/snowfall/modules/nixos/nh/default.nix
{
  src, # $HOME/nixos-config
  # root, # $HOME/nixos-config/snowfall
  ...
}: {
  programs.nh = {
    # ...
    flake = src;
  };
}
```

**Comment by jakehamilton** [comment]
You can access this value by using `lib.snowfall.fs.get-file "/"`

**Comment by jakehamilton** [comment]
If you need root then you can use the equivalent function `lib.snowfall.fs.get-snowfall-file`.

**Comment by songpola** [comment]
Oh! Thank you very much. I'll close this one. :)

**Comment by songpola** [comment]
Sorry, but I tried the `get-file` and it returns the nix store path:
`/nix/store/99cc9vbj82bsiwbcq14xli758yk133sx-d9bg2l52kwww5wdfaxyar9yvaq57qdiy-source/`,
not the real path: `/user-source`.

Is it working correctly?

**Comment by jakehamilton** [comment]
Yes that is working correctly. Your source is copied into the nix store.
