### ISSUE TITLE
Modules applied to every system causing breakages

### ISSUE THREAD

**Issue by arichtman** [snowfallorg/lib#8]
Hi Jake,

Hope you're feeling better!
Thanks so much for Snowfall to date and congrats on joining Replit!

I figured this was a better channel to try and work through the weird module/config application that was causing me to be unable to use one flake for both Mac and Linux.

Essentially, it seems that my WSL module is being applied to the Mac system despite configuration being controlled via an `enable` property. I've pared back all the other stuff to a minimal example. If I rename the `modules/wsl/default.nix` to anything other than `default.nix` I get some kind of infinite recursion error :(

It can be replicated by cloning this and running `nix eval .#darwinConfigurations.macbookpro`

https://github.com/arichtman/nix/tree/toy-mac

**Comment by jakehamilton** [comment]
Hey! Thanks for making this issue. I think it'll make this much easier to track. I'll see if I can reproduce this (though it may have to wait a few days).

**Comment by khaneliman** [comment]
I also had this issue with my config which caused me to just delete my mac config attempt, for now.

**Comment by jakehamilton** [comment]
I have some changes in the works that separate Darwin and NixOS systems, including their modules. The current version of Snowfall Lib loads all modules for all systems which can introduce these incompatibilities. Thanks again for reporting this :)

**Comment by arichtman** [comment]
Thanks for the early preview.
Good news is - the `feat/home-manager` branch seems to have removed the error where the other module was always applied. Bad news is - I'm struggling to get the modules to apply. I was working on my [actual implementation](https://github.com/arichtman/nix/tree/snowfall-mbp) when the modules for darwin or homes didn't seem to be applying to the host. I tried reproducing it on [my pared-back troubleshooting branch](https://github.com/arichtman/nix/tree/toy-mac) but it's just looping infinitely now. As before the test I'm using is cross-platform and should be `nix eval .#darwinConfigurations.macbookpro`

I'll keep trying, if I could put up a sample repository that might help others.

**Comment by khaneliman** [comment]
This seems to be resolved for me in the home-manager branch. Followed [Jake's Config](https://github.com/jakehamilton/config) and got it working in my [Khanelinix](https://github.com/khaneliman/khanelinix)

**Comment by arichtman** [comment]
This has been working for me a while I think and the dev branch has landed the changes. Thanks all for the help!
