### ISSUE TITLE
Can't install custom package

### ISSUE THREAD

**Issue by poperigby** [snowfallorg/lib#84]
This seems to be pretty similar to #42 but I can't glean any helpful information from it. I'm trying to install a custom install script to my ISO, but it's not working:

```nix
error: undefined variable 'poperigby'
at /nix/store/z94nwvfps7mymmvkvyqvg5g3h42j87b7-hl4p00x5j6ml8zap6w16klnlgf7rvwya-source/systems/x86_64-iso/iso/default.nix:24:9:
   23|         inputs.disko.packages.${pkgs.system}.disko
   24|         poperigby.installer
     |         ^
   25|     ];
```

My namespace is `poperigby` in my `flake.nix`: https://codeberg.org/PopeRigby/nixos/src/commit/59752ed006d5f0c2bca01ef6f8c76e651d9a9b66/flake.nix#L52

This is my custom package: https://codeberg.org/PopeRigby/nixos/src/commit/59752ed006d5f0c2bca01ef6f8c76e651d9a9b66/packages/installer/default.nix

Here's where I'm trying to include it in my ISO: https://codeberg.org/PopeRigby/nixos/src/commit/59752ed006d5f0c2bca01ef6f8c76e651d9a9b66/systems/x86_64-iso/iso/default.nix#L24

**Comment by jakehamilton** [comment]
`namespace` should be `snowfall.namespace`. You can find examples and reference in the project's documentation: https://snowfall.org/guides/lib/quickstart/#configure-snowfall-lib

**Comment by poperigby** [comment]
Oops, silly mistake. Thank you.
