### ISSUE TITLE
How do I run a shell?

### ISSUE THREAD

**Issue by YaroKasear** [snowfallorg/lib#85]
I am looking at the documentation for snowfall-lib about the shells and how they're done, but when I run nix-shell path/to/default.nix file where the shell is defined, I get:

```
> nix-shell ./shells/fabric/default.nix
error:
       … from call site

         at «none»:0: (source not available)

       error: function 'anonymous lambda' called without required argument 'lib'

       at /home/yaro/flakes/shells/fabric/default.nix:1:1:

            1| { lib, inputs, pkgs, stdenv, ... }:
             | ^
            2| with pkgs
```

It seems like using the nix-shell command isn't how I'm supposed to do it, maybe? Is there a "flake" command for this? I am trying to test a Python module and from what I read I can only do so in a Nix shell and this is not an aspect of Nix I know anything about.

**Comment by YaroKasear** [comment]
Okay, I figured out I do `nix shell .#devShells.x86-64-linux.fabric`

But now I have a new problem, nothing I put in the packages list seems to show up in my shell's PATH. 

```
{ lib, inputs, pkgs, stdenv, ... }:
with pkgs;

pkgs.mkShell {
  packages = [
    (python3.withPackages(ps: with ps; [
      united.python-fabric
    ]))
  ];
}
```

What I expect here is that typing "python" while in this shell will get into Python's repl. Instead I get command not found.

**Comment by jakehamilton** [comment]
You want `nix develop`, not `nix-shell` since you are working with flake dev shells.

for information on mkShell you'll want to look at the nixpkgs docs: https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-mkShell-usage

**Comment by YaroKasear** [comment]
Thanks for the help. I now have the module working. Now I need to make a script for Nix to wrap around so that I can use this properly the way the author intended.
