### ISSUE TITLE
Only allow certain unfree packages?

### ISSUE THREAD

**Issue by poperigby** [snowfallorg/lib#86]
I know you can allow all unfree packages with `channels-config.allowUnfree = true`, but I was wondering if it's possible to do so for individual packages.

**Comment by bestlem** [comment]
Yes you need to look at allowUnfreePredicate 
see [Nixos wiki](https://wiki.nixos.org/wiki/Unfree_Software)

**Comment by jakehamilton** [comment]
> @bestlem I was using `allowUnfreePredicate` and it wasn't working with Snowfall Lib:
> 
> ```nix
> nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
>     "steam"
>     "steam-original"
>     "steam-run"
> ];
> ```
> 
> https://codeberg.org/PopeRigby/nixos/src/commit/390d88cb9b7d7cd1ff21d8b450bb1dc153e23457/modules/nixos/suites/gaming/default.nix#L14
> 
> I was still saying that I needed to allow it after that block.

You need to pass it in channels-config, you can't use the `nixpkgs.config` module options due to passing in a `pkgs` set for the system.

**Comment by poperigby** [comment]
How exactly would I do that? Can I do `channels-config.allowUnfreePredicate`?

**Comment by jakehamilton** [comment]
> How exactly would I do that? Can I do `channels-config.allowUnfreePredicate`?

Yes, that attribute set is passed to nixpkgs when it is imported.

**Comment by poperigby** [comment]
Perfect, thanks!

**Comment by poperigby** [comment]
I was wondering if it's possible to use this within my flake:

```nix
{
  allowUnfreePredicate = pkg:
    builtins.elem (
      lib.getName pkg
    ) (
      map lib.getName [
        pkgs.corefonts
        pkgs.discord
        pkgs.jetbrains.idea-ultimate
        pkgs.spotify-unwrapped
        pkgs.unrar
      ]
    );
}
```

I tried this, but it's saying one of the binaries included within `epkowa` (`iscan-gt-f720-bundle`) isn't allowed.

```nix
channels-config.allowUnfreePredicate = pkg:
builtins.elem (
    inputs.nixpkgs.lib.getName pkg
) (
    builtins.map inputs.nixpkgs.lib.getName [
        inputs.nixpkgs.legacyPackages.x86_64-linux.epkowa
        inputs.nixpkgs.legacyPackages.x86_64-linux.steam
    ]
);
```

**Comment by jakehamilton** [comment]
@poperigby it may be better to post this on the NixOS forum, I don't believe this is Snowfall Lib related.
