### ISSUE TITLE
How do I remove home-manager from some systems?

### ISSUE THREAD

**Issue by mainrs** [snowfallorg/lib#87]
I have a bunch of systems that I declared using [microvm.nix](https://astro.github.io/microvm.nix/). My main user is under `homes/x86_64-linux/me/default.nix`. And these VMs also run under 64bit linux. Thus, the home-manager profile gets pulled in. 

Is there a way to disable this behavior for certain systems?

**Comment by pinkcreeper100** [comment]
maybe move `me` to `me@<hostname>`

**Comment by jakehamilton** [comment]
The docs for this are not available yet, but you can set `snowfallorg.users.me.home.enable = false;` to disable the automatic home-manager configuration for that user.

The other option is as @pinkcreeper100 suggests, creating individual homes for specific hosts.

**Comment by jakehamilton** [comment]
This should now be resolved in v3 :)
