### ISSUE TITLE
home manager partial application

### ISSUE THREAD

**Issue by evanrichter** [snowfallorg/lib#9]
first off, thanks for snowfall ❄️ ! As a relative newcomer to nix, I think the opinionated structure is going to help as I use nix to manage more hosts.

that said, I'm having trouble getting home manager applied (in full) for both nix-darwin and nixos hosts. I've used home-manager as a standalone flake before, but now I want to use it as a module.

Here's relevant info for how I'm using snowfall: [gist](https://gist.github.com/evanrichter/c026b020605409792c6f408751c67900)

In particular, my shell isn't being set to zsh although I have `programs.zsh.enable = true;` in my hm: https://gist.github.com/evanrichter/c026b020605409792c6f408751c67900#file-example-nix-L101-L103

And my home-manager environment variables aren't being set either, even if I set my shell to zsh using nixos config: `users.users.evan.shell = pkgs.zsh;`

My editor config, and all my `home.packages` are realized in my user shells, so home-manager is certainly being applied in part, just not the shell environment somehow.

Any help would be greatly appreciated!

**Comment by evanrichter** [comment]
update: the `sessionVariables` **are** being applied in a graphical environment (gnome) when I run the default console (kgx)

![image](https://user-images.githubusercontent.com/330292/236893091-4923da62-e90c-42e8-8604-63cfd5b2970a.png)

but still not in an ssh session. any ideas??

**Comment by jakehamilton** [comment]
Thanks for reporting this @evanrichter 🙏 

I haven't had time to try and reproduce this issue, but I do have some changes coming that introduce Home Manager support directly into Snowfall Lib. As for now, I'm not totally sure why your configuration isn't applying correctly. I would suggest looking at the generated `~/.zshrc` that Home Manager will link and see if it is actually being managed by Home Manager. My best guess is that the file is out of date and Home Manager is refusing to replace it.

**Comment by evanrichter** [comment]
~/.zshenv provided some clues: `__HM_SESS_VARS_SOURCED` and `__HM_ZSH_SESS_VARS_SOURCED` are getting set, so HM does activate my env at some point. I added `MYTESTVAR=woohoo` and it is set as expected.

Something is specifically overwriting my `EDITOR` back to nano, which turned out to be this issue: https://github.com/nix-community/home-manager/issues/3681

So adding `programs.zsh.enable = true;` to my nixos configuration as suggested did fix the issue
