### ISSUE TITLE
Module names are broken on the `main` branch

### ISSUE THREAD

**Issue by ivan770** [snowfallorg/lib#92]
`nixosModules` produced by Snowfall Lib have incorrect names that contain Nix store paths even in pure mode (IIRC should be possible only by discarding the string context).

To reproduce just run `nix flake show` on any flake that uses this library.

**Comment by jakehamilton** [comment]
Ah this ended up happening due to the fs helpers now returning paths. Apparently the returned path is now _different_ than the module source directory so the replacement wasn't working. This should be fixed now in the latest version.
