### ISSUE TITLE
Tags/branches and optimistic versioning

### ISSUE THREAD

**Issue by arichtman** [snowfallorg/lib#97]
Hey all,

I was wondering if there were thoughts around having either a mutable tag or long lived branch for say, v3. Presently it looks like options are either pessimistic versioning using precise pinning to tags, or just taking `main` directly.

Thanks!

**Comment by jakehamilton** [comment]
Would a solution like Thaw be acceptable? I think SemVer is the way to go here, the only trouble being that Nix does not have that tooling built in.

https://github.com/snowfallorg/thaw

**Comment by arichtman** [comment]
Yea that'll probably work, thanks!
